### PR TITLE
Add top margin to body when logged in.

### PR DESCRIPTION
**Pull request by mindctrl**
Prevents admin bar from covering up the top menu bar.

### CODE REVIEW

**Comment by rmccue** [comment]
Thanks for the pull request!

This should already be handled, is [this](https://github.com/rmccue/Feast-Razor/blob/master/style.css#L469) not working for you?

**Comment by mindctrl** [comment]
The #header is what's getting hidden.

**Comment by rmccue** [comment]
It looks fine to me; what version of WordPress are you running?

Capture

**Comment by mindctrl** [comment]
I'm on trunk. Tested in Firefox and Chromium on Mac. Same results. I'll test on 3.5.1, although that shouldn't matter.

feast-razor

**Comment by rmccue** [comment]
Huh, strange, I'm also on trunk (r23654), but on Windows. Your patch actually breaks it for me somewhat.

Capture

**Comment by mindctrl** [comment]
So, I'm looking at 3.5.1 and notice when logged in that WordPress adds inline style to the `html` element that does a `margin-top: 28px !important`. But in trunk it's not adding that. My trunk is 3.6-alpha-23791.

**Comment by rmccue** [comment]
Huh, strange, it is adding that for me in the source in `wp_head()`, not inline in the tag though.

Should be fixed in b3a220454fc7143f61f6c519ae6e71e8a7fd68fa?

**Comment by rmccue** [comment]
Whoops, that was a bad idea.

**Comment by mindctrl** [comment]
Oops, I meant in the head and not inline.

**Comment by rmccue** [comment]
Should be fixed in 677bff743bc260376cb7da813954a0d4bf6e3de6 instead.

**Comment by mindctrl** [comment]
Yes, that does the trick.

**Pull request closed without merging**
